SET(LIBRARY_PATHS
    HINTS
    ${CMAKE_INSTALL_PREFIX}
    PATH_SUFFIXES lib64 lib
    PATHS
    ${ILMBASE_ROOT}
    /usr/
    /usr/local/
    /opt/local/
)

FIND_PATH(ILMBASE_INCLUDE_DIR half.h
    HINTS
    ${CMAKE_INSTALL_PREFIX}
    PATH_SUFFIXES /OpenEXR
    PATHS
	${ILMBASE_ROOT}/include
    /usr/include       
    /usr/local/include  
    /opt/local/include
)

FIND_LIBRARY(ILMBASE_HALF_LIBRARY       NAMES Half      PATHS ${LIBRARY_PATHS})
FIND_LIBRARY(ILMBASE_IEX_LIBRARY        NAMES Iex       PATHS ${LIBRARY_PATHS})
FIND_LIBRARY(ILMBASE_IMATH_LIBRARY      NAMES Imath     PATHS ${LIBRARY_PATHS})
FIND_LIBRARY(ILMBASE_ILMTHREAD_LIBRARY  NAMES IlmThread PATHS ${LIBRARY_PATHS})

FIND_LIBRARY(ILMBASE_HALF_LIBRARYD       NAMES Halfd      PATHS ${LIBRARY_PATHS})
FIND_LIBRARY(ILMBASE_IEX_LIBRARYD        NAMES Iexd       PATHS ${LIBRARY_PATHS})
FIND_LIBRARY(ILMBASE_IMATH_LIBRARYD      NAMES Imathd     PATHS ${LIBRARY_PATHS})
FIND_LIBRARY(ILMBASE_ILMTHREAD_LIBRARYD  NAMES IlmThreadd PATHS ${LIBRARY_PATHS})

SET(ILMBASE_INCLUDE_DIRS ${ILMBASE_INCLUDE_DIR})
SET(ILMBASE_LIBRARIESO optimized ${ILMBASE_HALF_LIBRARY} optimized ${ILMBASE_ILMTHREAD_LIBRARY} optimized ${ILMBASE_IEX_LIBRARY} optimized ${ILMBASE_IMATH_LIBRARY})
SET(ILMBASE_LIBRARIESD debug ${ILMBASE_HALF_LIBRARYD} debug ${ILMBASE_ILMTHREAD_LIBRARYD} debug ${ILMBASE_IEX_LIBRARYD} debug ${ILMBASE_IMATH_LIBRARYD})

SET(ILMBASE_LIBRARIES ${ILMBASE_LIBRARIESO} ${ILMBASE_LIBRARIESD})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ILMBASE DEFAULT_MSG ILMBASE_INCLUDE_DIR ILMBASE_HALF_LIBRARY ILMBASE_IEX_LIBRARY ILMBASE_IMATH_LIBRARY ILMBASE_ILMTHREAD_LIBRARY)
